# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Cache Flutter packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            .packages
            pubspec.lock
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}


      - run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: Decode Keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > android/app/su-keystore.jks

      - name: Build Android APK
        run: flutter build apk --release

      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Build Android App Bundle
        run: flutter build appbundle --release

      - name: Upload Android App Bundle
        uses: actions/upload-artifact@v4
        with:
          name: app-bundle
          path: build/app/outputs/bundle/release/app-release.aab

  ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

  # ---- CocoaPods ----
      - name: Install CocoaPods and install Pod dependencies
        run: |
          sudo gem install cocoapods
          cd ios
          pod install --repo-update

      - name: List Xcode versions
        run: xcodebuild -version


    # Set up Xcode environment
      #- name: Set up Xcode
       # run: sudo xcode-select -s /Applications/Xcode.app

#Instal Ruby first before fastlane
      - name: Set up Ruby 3.1
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: false

      - name: Install dependencies
        run: |
          cd ios
            bundle config set --local path 'vendor/bundle'
            bundle install


 # ---- Install Fastlane ----
      #- name: Install fastlane
        #run: sudo gem install fastlane

      #Setup iOS signing (certificates & provisioning profiles)
      - name: Setup iOS Signing (Fastlane Match)
        env:
          APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_KEY: ${{ secrets.APP_STORE_CONNECT_KEY }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_PAT: ${{ secrets.MATCH_GIT_PAT }}
          
        run: |
          # Use HTTPS URL with secret expanded
          export MATCH_GIT_URL="https://$MATCH_GIT_PAT@github.com/JamperCin/su-ios-certificates.git"

      # Run Fastlane lanes
      - name: Run Fastlane build and upload
        env:
          APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_KEY: ${{ secrets.APP_STORE_CONNECT_KEY }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_PAT: ${{ secrets.MATCH_GIT_PAT }}
          MATCH_GIT_URL: https://${{ secrets.MATCH_GIT_PAT }}@github.com/JamperCin/su-ios-certificates.git

        run: |
          cd ios
            #echo "KEY_ID = $APP_STORE_CONNECT_API_KEY_ID"
            #export MATCH_GIT_URL="https://$MATCH_GIT_PAT@github.com/JamperCin/su-ios-certificates.git"
            bundle exec fastlane beta


